### PR TITLE
Fixed disposal of invalid memories and implemented OS Check Jit optimization

### LINKED ISSUE #352: Zero capacity Rust `Vec` creates invalid cast to `InteropArray` which invokes access violatation
When Rust side create a zero capacity `Vec` it uses [dangling pointer](https://doc.rust-lang.org/std/ptr/struct.NonNull.html#method.dangling) to avoid allocating invalid memory. And next `InteropArray` tries to `Dispose` not owned memory.

Probably good solution to this problem will be check if length of `InteropArray` is zero, and next check if pointer is dangling (use Rust implementation), and if true treat this the same like `null` in `Dispose` method.
https://github.com/NoiseStudio/NoiseEngine/blob/7a96cb8a24790f1e8130a634e6c7afea57f1b24e/NoiseEngine/Interop/InteropArray.cs#L132-L139

### PR DESCRIPTION
**Pull request by aaroniz-bgu**
Closes #352 and #70

Added `NoiseEngine.Common.MemoryHelper`, could add tests however these methods just use System's methods.

### CODE REVIEW

File: NoiseEngine/Common/MemoryHelper.cs [hunk 1]
```diff
@@ -0,0 +1,16 @@
+﻿using System;
+
+namespace NoiseEngine.Common;
+
+/// <summary>
+/// Collection of utility helpers memory management.
+/// </summary>
+internal static class MemoryHelper
```
Comment (Vixenka) [inline NoiseEngine/Common/MemoryHelper.cs:8]: Use our [C# code style](https://github.com/NoiseStudio/docs/blob/master/csharp/CodeStyle.md). I mean branches, also use `System.Runtime.InteropServices` in using, don't use one line methods, and end file with aditional empty line.

File: NoiseEngine/Interop/InteropArray.cs [hunk 2]
```diff
@@ -130,7 +131,7 @@ public struct InteropArray<T> : IDisposable, IReadOnlyList<T> where T : unmanage
     /// Disposes this object.
     /// </summary>
     public unsafe void Dispose() {
-        if (pointer == null)
+        if (pointer == null || MemoryHelper.IsDangling<T>((nuint)pointer) || Length <= 0)
```
Comment (Vixenka) [inline NoiseEngine/Interop/InteropArray.cs:134]: This should be `pointer == null || (Length == 0 && IsDangling())`, because you should check this only where Length is zero.

**Review by Vixenka — CHANGES_REQUESTED** [review]
Thanks for contributing! And for the future do not resolve two not related issues in one pull request for better readable and responsibility in review.

File: NoiseEngine/Interop/InteropArray.cs (hunk 2 above)
Comment (aaroniz-bgu) [reply NoiseEngine/Interop/InteropArray.cs]: Yep changed that, my bad.

File: NoiseEngine/Common/MemoryHelper.cs (hunk 1 above)
Comment (aaroniz-bgu) [reply NoiseEngine/Common/MemoryHelper.cs:8]: Fixed let me know if I missed something, Branch master was mistakenly assigned to this PR, there was one containing the naming format of other's that I've seen.

File: NoiseEngine/Interop/InteropArray.cs (hunk 2 above)
Comment (Vixenka) [reply NoiseEngine/Interop/InteropArray.cs]: You change it wrong. See how I wrote again.

**Review by Vixenka — APPROVED** [review]
Awesome, LGTM!
